# Regenerates data/Providers.kt from tools/providers.tsv
# Columns (tab separated): id, Greek name, category, website (unused), colour, English name (optional)
$root = Split-Path $PSScriptRoot -Parent
$lines = [IO.File]::ReadAllLines("$PSScriptRoot\providers.tsv", [Text.Encoding]::UTF8) | Where-Object { $_.Trim() }
$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('// Generated by tools/gen_providers.ps1 from tools/providers.tsv - do not edit by hand.')
[void]$sb.AppendLine("package gr.logariasmoi.data`n")
[void]$sb.AppendLine('data class Provider(val id: String, private val nameEl: String, val category: Category, val color: Long, private val nameEn: String? = null) {')
[void]$sb.AppendLine('    val name: String get() = tr(nameEl, nameEn ?: nameEl)')
[void]$sb.AppendLine('    val searchText: String get() = if (nameEn == null) nameEl else "$nameEl $nameEn"')
[void]$sb.AppendLine("}`n")
[void]$sb.AppendLine('object Providers {')
[void]$sb.AppendLine('    val all: List<Provider> = listOf(')
foreach ($l in $lines) {
    $p = $l -split "`t"
    $color = '0xFF' + $p[4].TrimStart('#')
    $en = if ($p.Count -gt 5 -and $p[5]) { ', "' + $p[5] + '"' } else { '' }
    [void]$sb.AppendLine('        Provider("' + $p[0] + '", "' + $p[1] + '", Category.' + $p[2] + ', ' + $color + $en + '),')
}
[void]$sb.AppendLine("    )`n")
[void]$sb.AppendLine('    private val byId = all.associateBy { it.id }')
[void]$sb.AppendLine('    fun get(id: String?): Provider? = id?.let { byId[it] }')
[void]$sb.AppendLine('}')
[IO.File]::WriteAllText("$root\app\src\main\java\gr\logariasmoi\data\Providers.kt", $sb.ToString(), (New-Object Text.UTF8Encoding $false))
"Providers: $($lines.Count)"
